### ISSUE TITLE
readme的composer 地址错了

### ISSUE THREAD

**Issue by pyj2004** [cccdl/adapay_sdk#1]
`$ composer require cccdl/yunxin_sdk`
应该是
`$ composer require cccdl/adapay_sdk`

另外支付回调没有封装吗？

**Comment by cccdl** [comment]
已经修改，你说的支付回调是什么？

**Comment by pyj2004** [comment]
> 已经修改，你说的支付回调是什么？

就是支付成功后的异步通知，我在BaseCore.php里加了一个函数：验签

    public function verifySign($signature, $data){
    	$pubKey = $this->adapayConfig->rsaPublicKey;
    	$key = "-----BEGIN PUBLIC KEY-----\n" . wordwrap($pubKey, 64, "\n", true) . "\n-----END PUBLIC KEY-----";
    	if (openssl_verify($data, base64_decode($signature), $key)){
    		return true;
    	}else{
    		return false;
    	}
    }

类似这样调用：

		$notify=$_POST;
		$post_data =  $notify ['data'];
		$signature = isset ( $notify ['sign'] ) ? $notify ['sign'] : '';
		$config = [
			"api_key_live" => "",
			"rsa_private_key" => "",
			"rsa_public_key" => ""
		];
		$adapayConfig = new \cccdl\adapay\Core\AdapayConfig ( $config );
		$service = new \cccdl\adapay\Payment\Payment ( $adapayConfig );
		$res = $service->verifySign ( $signature, $post_data );
		if ($res) {
				//回调成功
		}

**Comment by cccdl** [comment]
https://docs.adapay.tech/api/webhook.html#

**Comment by cccdl** [comment]
是不是这个异步通知

**Comment by cccdl** [comment]
有意向提交个PR吗

**Comment by pyj2004** [comment]
> 是不是这个异步通知
是的你把我上面那个验签加上应该可以了

public function verifySign($signature, $data){}

**Comment by cccdl** [comment]
已经添加了回调的版本了，你可以更新使用
